// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Programare_medic.Data;

#nullable disable

namespace Programare_medic.Migrations
{
    [DbContext(typeof(Programare_medicContext))]
    [Migration("20221213150534_SpitalTabel")]
    partial class SpitalTabel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Programare_medic.Models.Serviciu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<decimal>("Cost_consultatie")
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateTime>("Data_Programare")
                        .HasColumnType("datetime2");

                    b.Property<string>("Denumire_Serviciu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Medic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SpitalID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SpitalID");

                    b.ToTable("Serviciu");
                });

            modelBuilder.Entity("Programare_medic.Models.Spital", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("DenumireSpital")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Spital");
                });

            modelBuilder.Entity("Programare_medic.Models.Serviciu", b =>
                {
                    b.HasOne("Programare_medic.Models.Spital", "Spital")
                        .WithMany("Servicii")
                        .HasForeignKey("SpitalID");

                    b.Navigation("Spital");
                });

            modelBuilder.Entity("Programare_medic.Models.Spital", b =>
                {
                    b.Navigation("Servicii");
                });
#pragma warning restore 612, 618
        }
    }
}
